version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - npm install -g serverless
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - sls deploy
      - echo Done on `date`
